### PR TITLE
Support startup scripts compatible with multiple service names

### PR DESCRIPTION
**Pull request by huangxiaopingRD**
Related issues: https://github.com/apache/incubator-linkis/issues/3499

Test case:
image

### CODE REVIEW

**Comment by huangxiaopingRD** [comment]
@casionone  Can you help with a review? thanks

**Comment by casionone** [comment]
Other service names can also be supported together 
```
linkis-cg-engineconnmanager
linkis-cg-engineplugin
linkis-cg-entrance
linkis-cg-linkismanager
linkis-mg-gateway
linkis-ps-publicservice
```

**Comment by huangxiaopingRD** [comment]
> 

done

**Comment by huangxiaopingRD** [comment]
> Other service names can also be supported together
> 
> ```
> linkis-cg-engineconnmanager
> linkis-cg-engineplugin
> linkis-cg-entrance
> linkis-cg-linkismanager
> linkis-mg-gateway
> linkis-ps-publicservice
> ```

done

**Review by casionone — APPROVED** [review]
LGTM

**Pull request merged**
