### PR TITLE
[ISSUE-3319]Add publish-snapshot.yml action

### PR DESCRIPTION
**Pull request by casionone**
### What is the purpose of the change
Add publish-snapshot.yml action

### Related issues/PRs

Related issues: #3319 

### Checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [Linkis mailing list](https://linkis.apache.org/community/how-to-subscribe) first)
- [ ] **If this is a code change**: I have written unit tests to fully verify the new behavior.

### CODE REVIEW

**Review by jacktao007 — APPROVED** [review]
666

**Comment by jackxu2011** [comment]
这个有问题吧，看配置应该只有parent会变成snapshot

**Comment by jackxu2011** [comment]
> > 这个有问题吧，看配置应该只有parent会变成snapshot
> 
> yes,need to set new version mvnw versions:set -DnewVersion=xxx

according to the modifications,  the revision is useless, just mvnw versions:set -DnewVersion=xxx is enough

**Review by jackxu2011 — APPROVED** [review]
LGTM

**Pull request merged**
