### PR TITLE
upgrade poi and excel-streaming-reader

### PR DESCRIPTION
**Pull request by pjfanning**
### What is the purpose of the change
Upgrade POI and excel-streaming-reader to pick up security and other bug fixes.

Related issues: #1308 

### Brief change log
- Change dependencies
- Change licenses

### Verifying this change
This change is already covered by existing tests, such as (please describe tests).  

### Does this pull request potentially affect one of the following parts:
- Dependencies (does it add or upgrade a dependency): yes 
- Anything that affects deployment: no
- The MGS(Microservice Governance Services), i.e., Spring Cloud Gateway, OpenFeign, Eureka.: no

### Documentation
- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? not applicable

### CODE REVIEW

**Comment by pjfanning** [comment]
@peacewong could you approve the CI build when you get a chance?

**Comment by peacewong** [comment]
> @peacewong could you approve the CI build when you get a chance?

ok

**Comment by pjfanning** [comment]
@peacewong I'm not very familiar with the Linkis build - I'm not sure why the nodejs build timed out.

**Comment by peacewong** [comment]
> @peacewong I'm not very familiar with the Linkis build - I'm not sure why the nodejs build timed out.

Seems to be a github action issue, I restarted the build

**Review by peacewong — DISMISSED** [review]
LGTM.

**Comment by peacewong** [comment]
> @peacewong I'm not very familiar with the Linkis build - I'm not sure why the nodejs build timed out.
build is ok, because linkis 1.0.3-rc2 version is under voting, this pr will be merged into the latest code after version release

**Comment by peacewong** [comment]
> @peacewong I'm not very familiar with the Linkis build - I'm not sure why the nodejs build timed out.

build is ok, because linkis 1.0.3-rc2 version is under voting, this pr will be merged into the latest code after version release

**Comment by peacewong** [comment]
Please help to check the binary license @casionone

**Comment by casionone** [comment]
> Please help to check the binary license @casionone
I checked and it works fine for me.

**Comment by casionone** [comment]
@pjfanning 
In addition, for the scenario of dependent modification, I think it is necessary to add automatic verification checks to the git action in the future. 
Would you like to take this task?

**Review by peacewong — APPROVED** [review]
LGTM.

**Pull request merged**
