### PR TITLE
fix:https://github.com/apache/incubator-linkis/issues/1358

### LINKED ISSUE #1358: [Bug] the bug of SQLCodeParser
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### What happened + What you expected to happen

sql中含有';'时 不能正确切割SQL，如下图

When sql contains ';', the SQL cannot be cut correctly, as shown below：

image

### Relevent platform

scala jdk8

### Reproduction script

```scala
object CodeParserTest {
  def main(args: Array[String]): Unit = {
    val parser = new SQLCodeParser
    val sqlList = parser.parse(
      """
        select cast(CONCAT(a.brief,';',b.newstitle) AS VARCHAR) as mz_reason from test_table
      """.stripMargin)
    sqlList.foreach(x=>{
      println(x)
      println("----------")
    })
  }
}
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jianwei2**
### What is the purpose of the change
close #1358 

### Brief change log
-Optimize SqlCodeParser
-Semicolons inside double or single quotation marks are not considered delimiters

### Verifying this change
This change added tests and can be verified as follows:  
select * from xx where xx like '%abc;def%';
select * from xx where xx like '%abc;d"ef%';select * from xx where xx like '%a;d"ef%';
select * from xx where xx like '%abc;d\;ef%';

### Does this pull request potentially affect one of the following parts:
- Dependencies (does it add or upgrade a dependency): ( no)
- Anything that affects deployment: (no)
- The MGS(Microservice Governance Services), i.e., Spring Cloud Gateway, OpenFeign, Eureka.: ( no)

### Documentation
- Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by peacewong** [comment]
Hello, can this PR be submitted to the next released version dev-1.1.0-datasource

**Comment by jianwei2** [comment]
> Hello, can this PR be submitted to the next released version dev-1.1.0-datasource

ok. What different between dev-1.1.0-datasource and dev-1.3.0 ？

**Comment by peacewong** [comment]
> > Hello, can this PR be submitted to the next released version dev-1.1.0-datasource
> 
> ok. What different between dev-1.1.0-datasource and dev-1.3.0 ？

dev-1.1.0 will be released sooner, this bug fix is better in this version

**Comment by jianwei2** [comment]
> 

ok

**Comment by peacewong** [comment]
Thanks, how can I get your contact information  so that you can join the development community? Or you can contact my email, [peacewong@apache.org](mailto:peacewong@apache.org)

**Comment by jianwei2** [comment]
> > > Hello, can this PR be submitted to the next released version dev-1.1.0-datasource
> > 
> > 
> > ok. What different between dev-1.1.0-datasource and dev-1.3.0 ？
> 
> dev-1.1.0 will be released sooner, this bug fix is better in this version

ok，got it

**Comment by jianwei2** [comment]
> Thanks, how can I get your contact information so that you can join the development community? Or you can contact my email, [peacewong@apache.org](mailto:peacewong@apache.org)

afweijian@163.com
I updated my profile.

**Comment by jianwei2** [comment]
Closed this,resubmitted at https://github.com/apache/incubator-linkis/pull/1446

**Pull request closed without merging**
