### PR TITLE
[WIP]add test case for [linkis-scheduler] #1914

### PR DESCRIPTION
**Pull request by QuintinTao**
### What is the purpose of the change
 Added tests for  linkis-scheduler package

### CODE REVIEW

**Comment by peacewong** [comment]
Thanks, I will review this

**Review by peacewong — APPROVED** [review]
LGTM.

**Comment by peacewong** [comment]
Hello, the username in your commit may be inconsistent with GitHub, so that it will not be counted as contributor, and you need to reset it.

**Comment by QuintinTao** [comment]
> me in your commit may be inconsistent with GitHub, so that it will not be counted as contributor, and

OK I will correct it soon.

**Pull request merged**
