### PR TITLE
Add some target directories into .gitignore

### PR DESCRIPTION
**Pull request by asdf2014**
### What is the purpose of the change

This patch adds some target directories into `.gitignore` to ignore them.

### CODE REVIEW

**Comment by asdf2014** [comment]
Specifically these files under these target directories, as follows:
image

**Review by peacewong — APPROVED** [review]
LGTM.

**Comment by peacewong** [comment]
Hello, please submit to dev-1.0.3 branch

**Comment by asdf2014** [comment]
@peacewong Thanks for your comment. https://github.com/apache/incubator-linkis/pull/1130 has been created please take a look, I will close this one.

**Pull request closed without merging**
