### PR TITLE
Add codecov git action to track test coverage metrics

### PR DESCRIPTION
**Pull request by husofskyzy**
### What is the purpose of the change
add codecov git action to track test coverage metrics  #1946 

### Verifying this change
This change is a trivial rework / code cleanup without any test coverage.  

### Does this pull request potentially affect one of the following parts:
- Dependencies (does it add or upgrade a dependency): (yes)

### CODE REVIEW

**Review by peacewong — APPROVED** [review]
LGTM.

**Comment by casionone** [comment]
https://github.com/apache/incubator-linkis/runs/5983197735?check_suite_focus=true
```
[2022-04-12T03:08:46.318Z] ['info'] => Project root located at: /home/runner/work/incubator-linkis/incubator-linkis
[2022-04-12T03:08:46.319Z] ['info'] -> No token specified or token is empty
[2022-04-12T03:08:46.332Z] ['info'] Searching for coverage files...
[2022-04-12T03:08:47.1[25](https://github.com/apache/incubator-linkis/runs/5983197735?check_suite_focus=true#step:7:25)Z] ['info'] Warning: Some files located via search were excluded from upload.
[2022-04-12T03:08:47.125Z] ['info'] If Codecov did not locate your files, please review https://docs.codecov.com/docs/supported-report-formats
[2022-04-12T03:08:47.125Z] ['error'] There was an error running the uploader: No coverage files located, please try use `-f`, or change the project root with `-R`
```
Some  error log info  ` ['error'] There was an error running the uploader: No coverage files located, please try use `-f`, or change the project root with `-R`

**Review by casionone — APPROVED** [review]

**Review by peacewong — APPROVED** [review]
LGTM.

**Comment by javeme** [comment]
@husofskyzy Hi, I'm from the Apache HugeGraph(incubator) team, and we are currently encountering a [codecov issue](https://github.com/apache/incubator-hugegraph/issues/1836), Can I ask some questions?

After we migrated the [hugegraph project](https://github.com/apache/incubator-hugegraph) to apache, codecov could not send the report to the github PR. It seems OK for [linkis PR](https://github.com/apache/incubator-linkis/pull/1945#issuecomment-1096580910), what operations you have done? Do you installed the codecov app for linkis repository? Thanks~

**Comment by husofskyzy** [comment]
> @husofskyzy Hi, I'm from the Apache HugeGraph(incubator) team, and we are currently encountering a [codecov issue](https://github.com/apache/incubator-hugegraph/issues/1836), Can I ask some questions?
> 
> After we migrated the [hugegraph project](https://github.com/apache/incubator-hugegraph) to apache, codecov could not send the report to the github PR. It seems OK for [linkis PR](https://github.com/apache/incubator-linkis/pull/1945#issuecomment-1096580910), what operations you have done? Do you installed the codecov app for linkis repository? Thanks~

yes,we have installed the codecov app.you can see the file change in this PR.

**Comment by javeme** [comment]
Thank you.
We also update [.github/workflows/ci.yml](https://github.com/apache/incubator-hugegraph/pull/1834/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL96), but codecov still could not send the report to the github PR. Do you mean the codecov app is installed in github `settings/installations` location https://github.com/apache/incubator-linkis/settings/installations ?

Like this location:
image

**Pull request merged**
