### PR TITLE
Check env JAVA_HOME firstly before set

### PR DESCRIPTION
**Pull request by legendtkl**
fix for https://github.com/apache/incubator-linkis/issues/1146

### CODE REVIEW

**Comment by legendtkl** [comment]
@peacewong  Would you help review this PR?

thanks.

**Comment by peacewong** [comment]
> @peacewong Would you help review this PR?
> 
> thanks.

@Fuu3214

**Comment by wayson20** [comment]
Yes, I install jdk in other path and set JAVA_HOME env in .bashrc, those scripts can‘t find it. This pr fix it.

**Review by peacewong — APPROVED** [review]
LGTM.

**Pull request merged**
