### PR TITLE
Downgrading jackson to 2.12.7

### PR DESCRIPTION
**Pull request by casionone**
### What is the purpose of the change
upgrade jackson-bom.version 2.13.2.1 to 2.13.2.2

### CODE REVIEW

**Comment by jackxu2011** [comment]
the hadoop has downgrade jackson to 2.12.7 to fit jsr311

**Comment by casionone** [comment]
> the hadoop has downgrade jackson to 2.12.7 to compatible with jsr311

jackson-databind 2.13.2.1 has high security vulnerability  
Does you mean that there will be incompatibility with jsr311 after the upgrade?
Is there a related issue or an announcement

**Comment by jackxu2011** [comment]
> > the hadoop has downgrade jackson to 2.12.7 to compatible with jsr311
> 
> jackson-databind 2.13.2.1 has high security vulnerability Does you mean that there will be incompatibility with jsr311 after the upgrade? Is there a related issue or an announcement

2.12.7 has no security vulnerability

**Comment by casionone** [comment]
> > > the hadoop has downgrade jackson to 2.12.7 to compatible with jsr311
> > 
> > 
> > jackson-databind 2.13.2.1 has high security vulnerability Does you mean that there will be incompatibility with jsr311 after the upgrade? Is there a related issue or an announcement
> 
> 2.12.7 has no security vulnerability

Is it recommended to use jackson bom version of 2.12.7?

**Comment by jackxu2011** [comment]
> > > > the hadoop has downgrade jackson to 2.12.7 to compatible with jsr311
> > > 
> > > 
> > > jackson-databind 2.13.2.1 has high security vulnerability Does you mean that there will be incompatibility with jsr311 after the upgrade? Is there a related issue or an announcement
> > 
> > 
> > 2.12.7 has no security vulnerability
> 
> Is it recommended to use jackson bom version of 2.12.7?

yes see https://issues.apache.org/jira/browse/HADOOP-18332

**Pull request merged**
