### PR TITLE
Merge dev-1.1.2 into master

### PR DESCRIPTION
**Pull request by casionone**

### CODE REVIEW

**Review by peacewong — APPROVED** [review]
LGTM.

**Comment by CCweixiao** [comment]
LGTM.

**Review by CCweixiao — COMMENTED** [review]
LGTM.

**Comment by CCweixiao** [comment]
> # [Codecov](https://codecov.io/gh/apache/incubator-linkis/pull/2296?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation) Report
> > Merging [#2296](https://codecov.io/gh/apache/incubator-linkis/pull/2296?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation) ([4830ad8](https://github.com/apache/incubator-linkis/commit/4830ad8552823a2b5b931bfaf930800cd956187b)) into [master](https://codecov.io/gh/apache/incubator-linkis/commit/1a3a1eea6cdaa006bb7f7d705e51fff2ea15ef60?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation) ([1a3a1ee](https://github.com/apache/incubator-linkis/commit/1a3a1eea6cdaa006bb7f7d705e51fff2ea15ef60)) will **decrease** coverage by `0.17%`.
> > The diff coverage is `n/a`.
> 
> ```diff
> @@             Coverage Diff              @@
> ##             master    #2296      +/-   ##
> ============================================
> - Coverage     19.62%   19.44%   -0.18%     
> - Complexity      843      989     +146     
> ============================================
>   Files           383      440      +57     
>   Lines         11819    13280    +1461     
>   Branches       1757     2154     +397     
> ============================================
> + Hits           2319     2582     +263     
> - Misses         9257    10359    +1102     
> - Partials        243      339      +96     
> ```
> 
> [Impacted Files](https://codecov.io/gh/apache/incubator-linkis/pull/2296?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation)	Coverage Δ	
> [...he/linkis/cli/core/exception/CommandException.java](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-bGlua2lzLWNvbXB1dGF0aW9uLWdvdmVybmFuY2UvbGlua2lzLWNsaWVudC9saW5raXMtY2xpL2xpbmtpcy1jbGktY29yZS9zcmMvbWFpbi9qYXZhL29yZy9hcGFjaGUvbGlua2lzL2NsaS9jb3JlL2V4Y2VwdGlvbi9Db21tYW5kRXhjZXB0aW9uLmphdmE=)	`0.00% <0.00%> (-100.00%)`	⬇️
> [.../linkis/cli/core/exception/error/CommonErrMsg.java](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-bGlua2lzLWNvbXB1dGF0aW9uLWdvdmVybmFuY2UvbGlua2lzLWNsaWVudC9saW5raXMtY2xpL2xpbmtpcy1jbGktY29yZS9zcmMvbWFpbi9qYXZhL29yZy9hcGFjaGUvbGlua2lzL2NsaS9jb3JlL2V4Y2VwdGlvbi9lcnJvci9Db21tb25FcnJNc2cuamF2YQ==)	`0.00% <0.00%> (-93.94%)`	⬇️
> [...ava/org/apache/linkis/cli/core/utils/LogUtils.java](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-bGlua2lzLWNvbXB1dGF0aW9uLWdvdmVybmFuY2UvbGlua2lzLWNsaWVudC9saW5raXMtY2xpL2xpbmtpcy1jbGktY29yZS9zcmMvbWFpbi9qYXZhL29yZy9hcGFjaGUvbGlua2lzL2NsaS9jb3JlL3V0aWxzL0xvZ1V0aWxzLmphdmE=)	`0.00% <0.00%> (-60.00%)`	⬇️
> [...ore/exception/handler/CommandExceptionHandler.java](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-bGlua2lzLWNvbXB1dGF0aW9uLWdvdmVybmFuY2UvbGlua2lzLWNsaWVudC9saW5raXMtY2xpL2xpbmtpcy1jbGktY29yZS9zcmMvbWFpbi9qYXZhL29yZy9hcGFjaGUvbGlua2lzL2NsaS9jb3JlL2V4Y2VwdGlvbi9oYW5kbGVyL0NvbW1hbmRFeGNlcHRpb25IYW5kbGVyLmphdmE=)	`9.09% <0.00%> (-45.46%)`	⬇️
> [...ore/exception/handler/DefaultExceptionHandler.java](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-bGlua2lzLWNvbXB1dGF0aW9uLWdvdmVybmFuY2UvbGlua2lzLWNsaWVudC9saW5raXMtY2xpL2xpbmtpcy1jbGktY29yZS9zcmMvbWFpbi9qYXZhL29yZy9hcGFjaGUvbGlua2lzL2NsaS9jb3JlL2V4Y2VwdGlvbi9oYW5kbGVyL0RlZmF1bHRFeGNlcHRpb25IYW5kbGVyLmphdmE=)	`0.00% <0.00%> (-31.43%)`	⬇️
> [...li/core/interactor/command/CmdTemplateFactory.java](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-bGlua2lzLWNvbXB1dGF0aW9uLWdvdmVybmFuY2UvbGlua2lzLWNsaWVudC9saW5raXMtY2xpL2xpbmtpcy1jbGktY29yZS9zcmMvbWFpbi9qYXZhL29yZy9hcGFjaGUvbGlua2lzL2NsaS9jb3JlL2ludGVyYWN0b3IvY29tbWFuZC9DbWRUZW1wbGF0ZUZhY3RvcnkuamF2YQ==)	`0.00% <0.00%> (-15.39%)`	⬇️
> [...inkis/jobhistory/conversions/TaskConversions.scala](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-bGlua2lzLXB1YmxpYy1lbmhhbmNlbWVudHMvbGlua2lzLXB1YmxpY3NlcnZpY2UvbGlua2lzLWpvYmhpc3Rvcnkvc3JjL21haW4vc2NhbGEvb3JnL2FwYWNoZS9saW5raXMvam9iaGlzdG9yeS9jb252ZXJzaW9ucy9UYXNrQ29udmVyc2lvbnMuc2NhbGE=)	`7.89% <0.00%> (-0.68%)`	⬇️
> [.../org/apache/linkis/common/conf/Configuration.scala](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-bGlua2lzLWNvbW1vbnMvbGlua2lzLWNvbW1vbi9zcmMvbWFpbi9zY2FsYS9vcmcvYXBhY2hlL2xpbmtpcy9jb21tb24vY29uZi9Db25maWd1cmF0aW9uLnNjYWxh)	`0.00% <0.00%> (ø)`	
> [...org/apache/linkis/common/utils/VariableUtils.scala](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-bGlua2lzLWNvbW1vbnMvbGlua2lzLWNvbW1vbi9zcmMvbWFpbi9zY2FsYS9vcmcvYXBhY2hlL2xpbmtpcy9jb21tb24vdXRpbHMvVmFyaWFibGVVdGlscy5zY2FsYQ==)	`0.00% <0.00%> (ø)`	
> [.../scala/org/apache/linkis/scheduler/queue/Job.scala](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-bGlua2lzLWNvbW1vbnMvbGlua2lzLXNjaGVkdWxlci9zcmMvbWFpbi9zY2FsYS9vcmcvYXBhY2hlL2xpbmtpcy9zY2hlZHVsZXIvcXVldWUvSm9iLnNjYWxh)	`14.21% <0.00%> (ø)`	
> ... and [59 more](https://codecov.io/gh/apache/incubator-linkis/pull/2296/diff?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation)		
> [Continue to review full report at Codecov](https://codecov.io/gh/apache/incubator-linkis/pull/2296?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/apache/incubator-linkis/pull/2296?src=pr&el=footer&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation). Last update [1a3a1ee...4830ad8](https://codecov.io/gh/apache/incubator-linkis/pull/2296?src=pr&el=lastupdated&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation).

**Review by CCweixiao — COMMENTED** [review]
LGTM.

**Review by CCweixiao — APPROVED** [review]

**Pull request merged**
