### PR TITLE
fix client unsupport -runtimeMap param #1601

### PR DESCRIPTION
**Pull request by ganlangjie**
fix client unsupport **-runtimeMap** param
[https://github.com/apache/incubator-linkis/issues/1601](url)

### CODE REVIEW

**Comment by peacewong** [comment]
> fix client unsupport **-runtimeMap** param [https://github.com/apache/incubator-linkis/issues/1601](url)

Thanks!

**Review by Fuu3214 — CHANGES_REQUESTED** [review]
Thx for the commit, but I’m afraid this won’t work. You need to pass input runtimeMap params to LinkisJob via VarAccess. You can refer to code in LinkisJobBuilder. 
By the way, we have already added -runtimeMap option in 1.1.1 version. And it will be released very soon. So you can also put this problem aside and wait for us to handle it.

Shang

**Comment by ganlangjie** [comment]
OK

**Review by peacewong — APPROVED** [review]
LGTM.

**Pull request merged**
