### PR TITLE
[Feat] use uniform linkis version

### LINKED ISSUE #4018: [Bug] use uniform linkis version
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### Steps to reproduce

currently once we need to release a new version, we need to change all version files, we can add the version in common properties.

### Expected behavior

we will only need to change the common properties if we want to release a new version

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by GuoPhilipse**
fix #4018

### CODE REVIEW

**Review by casionone — APPROVED** [review]
LGTM

**Comment by peacewong** [comment]
Need to delete file : linkis-spring-cloud-services/linkis-service-gateway/plugins/linkis-gateway-datasource-ruler/pom.xml

**Review by peacewong — DISMISSED** [review]
LGTM.

**Comment by peacewong** [comment]
The jdbc-drver module needs to be included

**Comment by GuoPhilipse** [comment]
> 

done

**Comment by GuoPhilipse** [comment]
> Need to delete file : linkis-spring-cloud-services/linkis-service-gateway/plugins/linkis-gateway-datasource-ruler/pom.xml

fixed

**Review by peacewong — APPROVED** [review]
LGTM.

**Pull request merged**
