### PR TITLE
[Optimize] move to the end and add try catch block to ensure execute

### PR DESCRIPTION
**Pull request by guoshupei**
### Related issues/PRs

Related issues: #3832

### CODE REVIEW

**Comment by casionone** [comment]
run `mvn spotless:apply` to format code style

**Comment by guoshupei** [comment]
OK，I run command and no changes detected.

**Comment by guoshupei** [comment]
> run `mvn spotless:apply` to format code style

Hi, @casionone , I run command and no changes detected.
8a68e78a-3664-4af8-944f-3ed4e7592d7f

**Review by peacewong — APPROVED** [review]
LGTM.

**Pull request merged**
