### PR TITLE
issue-4004: upgrade commons-net to 3.9.0

### PR DESCRIPTION
**Pull request by pjfanning**
### What is the purpose of the change

upgrade commons-net to 3.9.0 due to cve

### Related issues/PRs

Related issues: #4004

### Brief change log

- upgrade pom

### Checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] I have explained the need for this PR and the problem it solves
- [ ] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [ ] I have verified that this change is backward compatible (If not, please discuss on the [Linkis mailing list](https://linkis.apache.org/community/how-to-subscribe) first)
- [ ] **If this is a code change**: I have written unit tests to fully verify the new behavior.

### CODE REVIEW

**Review by peacewong — APPROVED** [review]
LGTM.

**Review by casionone — APPROVED** [review]

**Review by casionone — CHANGES_REQUESTED** [review]
need to remove `commons-net-3.1.jar`

**Comment by pjfanning** [comment]
> for known-dependencies.txt need to remove `commons-net-3.1.jar`

the know-dependencies check fails if that line is removed - maybe some other dependency is pulling that in as a transitive dependency

**Review by casionone — APPROVED** [review]

**Review by peacewong — APPROVED** [review]
LGTM.

**Pull request merged**
