### PR TITLE
issue-3640: upgrade to 2.13.4.20221013 due to CVE fixes

### PR DESCRIPTION
**Pull request by pjfanning**
### What is the purpose of the change

Security issue with jackson

### Related issues/PRs

Related issues: #3640

### Brief change log

- version changes

### Checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] I have explained the need for this PR and the problem it solves
- [x] I have explained the changes or the new features added to this PR
- [ ] I have added tests corresponding to this change
- [ ] I have updated the documentation to reflect this change
- [x] I have verified that this change is backward compatible (If not, please discuss on the [Linkis mailing list](https://linkis.apache.org/community/how-to-subscribe) first)
- [ ] **If this is a code change**: I have written unit tests to fully verify the new behavior.

### CODE REVIEW

**Comment by jackxu2011** [comment]
this release still have CVE, wait for next release

**Comment by pjfanning** [comment]
@jackxu2011 I'm a member of the fasterxml/jackson team - this version of jackson has all the CVE fixes - described in https://github.com/apache/incubator-linkis/issues/3640

**Comment by pjfanning** [comment]
2,12.7.1 is released - https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.7.1/

Linkis currently uses 2.13.2.1 and there are no problems. 2.13.4 is a minor upgrade from that. I'm not sure it would be a good idea to revert back to 2.12.x.

**Comment by jackxu2011** [comment]
> 2.12.7.1 is released - https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.7.1/
> 
> Linkis currently uses 2.13.2.1 and there are no problems. 2.13.4 is a minor upgrade from that. I'm not sure it would be a good idea to revert back to 2.12.x.

2.13 have a compatibility problem with  jersey.

**Comment by pjfanning** [comment]
jersey-core/jersey-json 1.19 does not even use Jackson2 - it uses Jackson1 which has completey different package names (org.codehaus.jackson).
I am a member of the Jackson dev team - I know a bit about how Jackson works.

**Comment by jackxu2011** [comment]
> jersey-core/jersey-json 1.19 does not even use Jackson2 - it uses Jackson1 which has completey different package names (org.codehaus.jackson). I am a member of the Jackson dev team - I know a bit about how Jackson works.

it's not the jackson itself,  but the dependencies.

**Review by peacewong — APPROVED** [review]
LGTM.

**Review by jackxu2011 — APPROVED** [review]

**Pull request merged**
